### ISSUE TITLE
SonarQube build should support dynamic plugin list

### ISSUE THREAD

**Issue by oybed** [redhat-cop/containers-quickstarts#204]
SonarQube currently has a hardcoded list of plugins in the Dockerfile - i.e.: `pmd gitlab github ldap` . The build should support a dynamic list passed through the build template. 

Also, the list of plugins should also support sourcing files from **any** URLs

**Comment by mcanoy** [comment]
@oybed that list is the default list. you can change the value (or any ARG/ENV value) with 
```
oc start-build sonarqube -n sonarqube --build-arg=sonar_plugins=swift --follow
```

or in the bc

```
...
  strategy:
    dockerStrategy:
      buildArgs:
      - name: sonar_plugins
        value: swift
      from:
        kind: ImageStreamTag
        name: sonarqube:latest
    type: Docker
```
