### ISSUE TITLE
the user id is no longer being automatically added to passwd for any of the worker images

### ISSUE THREAD

**Issue by itewk** [redhat-cop/containers-quickstarts#214]
it used to be that "something" (i thought something in the jenkins-slave-base image) injected the UID into the passwd, but building and using the latest images in this repo and checking the passwd file that is not happening which is causing all sorts of other issues with things like git.

**Comment by oybed** [comment]
Yes, this is handled by the /usr/local/bin/generate_container_user script in the base image. This is sourced from the entrypoint ( `run-jnlp-client` ) and hence should take acre of the problem.

https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L16

**Comment by itewk** [comment]
i was able to fix this by doing the following:

```
agent {
            kubernetes {
                label "jenkins-${env.SERVICE_NAME}-${env.BUILD_ID}"
                defaultContainer 'jenkins-worker-nodejs10'
                cloud 'openshift'
                yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: 'jnlp'
  - name: 'jenkins-worker-nodejs10'
    image: docker-registry.default.svc:5000/madss-ci-cd/jenkins-slave-nodejs10:latest
    tty: true
    command: ['sh', '-c', 'generate_container_user && cat']
  - name: 'jenkins-slave-ansible'
    image: docker-registry.default.svc:5000/madss-ci-cd/jenkins-slave-ansible:latest
    tty: true
    command: ['sh', '-c', 'generate_container_user && cat']
  - name: 'jenkins-worker-image-mgmt'
    image: docker-registry.default.svc:5000/madss-ci-cd/jenkins-slave-image-mgmt:latest
    tty: true
    command: ['sh', '-c', 'generate_container_user && cat']
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/dockerconfigjson
      name: dockerconfigjson
      readOnly: true
  volumes:
  - name: dockerconfigjson 
    secret:
      secretName: dockerconfigjson
"""
```

it would seem that something changed in the base image. i thought this `generate_container_user` or equivlant was auto called before, and now i have to explicatly call it.
